-- ══════════════════════════════════════════════════════════════
-- WF Schema Migration 002 (OBSOLETE — intentionally a no-op)
-- ══════════════════════════════════════════════════════════════
-- เดิมไฟล์นี้ตั้งใจ refactor: DROP wf.SalesOrder / SalesOrderLine แล้วย้ายไป
-- เก็บที่ dbo.SOHD + wf.SalesOrderExt ("single source of truth")
--
-- แต่แผนนี้ถูกยกเลิก:
--   • wf.SalesOrder / wf.SalesOrderLine ยังจำเป็น (เก็บ DRAFT order ของ App)
--     และถูกอ้างโดย v_AllSalesOrders (007/009) + sp_ConfirmSalesOrder
--   • ตาราง Ext ถูกสร้างจริงโดย 003_schema_ext.sql (พร้อม FK ที่ถูกต้อง)
--   • RebateLedger / SalesOrderAudit มาจาก 001 + ALTER ใน 003
--
-- นอกจากนี้ migration เดิมจะ FAIL เสมอ (DROP wf.RebateLedger ติด FK
-- FK__RebateUsa__Ledge__* จาก wf.RebateUsage ที่สร้างใน 010) แล้ว rollback
-- ทั้ง transaction → ไม่เคยมีผลกับ DB ใดเลย
--
-- จึงเปลี่ยนเป็น no-op เพื่อให้ migration รัน clean (0 errors) และคงเลขลำดับไว้
-- ⚠ ห้ามนำ DROP เดิมกลับมา — จะลบ wf.SalesOrder/SalesOrderLine ทิ้ง
PRINT 'Migration 002 is obsolete (no-op). See 001 + 003 for the live wf schema.';
