-- =============================================================
-- 011_seed_sales_users_giveaway.sql
-- Create missing sales AppUsers
-- Safe to re-run: uses IF NOT EXISTS guards
--
-- NOTE: การ seed GiveawayBudget ย้ายไปอยู่ที่ 012_seed_giveaway_budget.sql
--       (schema ใหม่ใช้ Region/Brand/ItemName/BudgetQty ไม่ใช่ TotalBudget/UsedAmt)
--       section เดิมถูกลบออกเพราะอ้างคอลัมน์ที่เลิกใช้แล้ว → migrate รัน clean
-- =============================================================

-- [REMOVED] Hardcoded users have been removed in favor of syncing directly from EMEmp (049_seed_all_employees.sql).
